services:
    db:
        build:
            context: ./docker
            dockerfile: db.dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./db-data:/var/lib/mysql

    httpd:
        build:
            context: ./docker
            dockerfile: httpd.dockerfile
        depends_on:
            - db
        ports:
            - 80:80
            - 443:443
        restart: always
        extra_hosts:
            - ${WP_DOMAIN}:127.0.0.1
        volumes:
            - ./docker/php.ini:/usr/local/etc/php.ini:ro
            - ./html:/var/www/html

    dev:
        build:
            context: ./docker
            dockerfile: dev.dockerfile
        depends_on:
            - db
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            WP_DOMAIN: ${WP_DOMAIN}
            WP_TITLE: ${WP_TITLE}
            WP_ADMIN_USER: ${WP_ADMIN_USER}
            WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
            WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        volumes:
            - ./docker/php.ini:/usr/local/etc/php.ini
            - ./docker/dev-scripts:/home/dev/scripts
            - ./html:/var/www/html

    adminer:
        image: adminer:latest
        depends_on:
            - db
        restart: always
        ports:
            - 8080:8080
